### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by olmlet** [AnkouOSRS/cox-light-colors#1]
Have you not created a code yet for cox light colors?  @AnkouOSRS

**Comment by AnkouOSRS** [comment]
> Have you not created a code yet for cox light colors? @AnkouOSRS

The code is in this repository?

**Comment by olmlet** [comment]
I couldn't get code to work. It's your name and cox-light-colors.  Right?  I i typed that in repository says invalid. @AnkouOSRS

**Comment by olmlet** [comment]
I'm not sure what I'm suppose to be typing, New to this

**Comment by AnkouOSRS** [comment]
I'm not really sure what you're looking for. If you just want to use the plugin you can get it in the Runelite Plugin Hub. If you would like to view the code you can find that here:

https://github.com/AnkouOSRS/cox-light-colors/tree/master/src/main/java/com/coxlightcolors

If you'd like to modify or run the code you can clone this repository that you opened this issue for, modify those files, then run the test that is included to launch the client with the plugin
