### ISSUE TITLE
different client

### ISSUE THREAD

**Issue by alsokaneki** [AnkouOSRS/cox-light-colors#3]
im using open and i cant find out how to add the reposit correctly to get the plugin to work could i get some help or even told if its possible?

**Comment by olmlet** [comment]
That's my problem too.  I don't think it's on open yet

**Comment by AnkouOSRS** [comment]
I have no idea how open handles plugin hub plugins so I wouldn't be able to address that issue. The plugin was developed for standard runelite and I don't personally plan on using or developing for another 3rd party client.
