### ISSUE TITLE
Plugin sometimes changes player model's color

### ISSUE THREAD

**Issue by ThatGamerBlue** [AnkouOSRS/cox-light-colors#8]
Been seeing this issue for a while now and have narrowed it down to this plugin, not sure why or how it does it but figured i might as well tell you. 
![greenplayer](https://user-images.githubusercontent.com/29176781/92226434-a47a2a80-ee9c-11ea-9f8c-324923059779.png)

**Comment by AnkouOSRS** [comment]
I've actually had this happen on rare occasion, equipping an item fixes it but I'm hoping to resolve this issue for the next update.

**Comment by AnkouOSRS** [comment]
Fixed in 1.3.3
