### ISSUE TITLE
Light colors not changing

### ISSUE THREAD

**Issue by buggertitsup** [AnkouOSRS/cox-light-colors#9]
Hi, I'm not sure what I'm doing wrong, but the plugin doesn't seem to be working for me.

I set up items in groups, and I left drops I still haven't received without a group.
So new unique items should be purple light, then dupes blue/yellow/red depending on their category.

Every time I get a drop, it is just the standard purple light, even if item is a dupe in a category that has it's own light.

I have my game tab as the only one open during olm, so I don't see drop in chat. I tried changing color settings after I checked the drop and it simply always stays purple. Like, I got a dupe kodai, which I selected to be blue category, and the color is still purple.

Any insight into how to get it working? Maybe something to do with other Runelite settings?

**Comment by AnkouOSRS** [comment]
I've actually heard of this issue occurring to a few people and at the moment I'm not exactly sure what is causing it. Very unfortunate but I will continue to investigate.

**Comment by AnkouOSRS** [comment]
The most recent updates should hopefully help to resolve this issue but if anyone still experiences it please provide me the relevant section of your client.log file after receiving the unique.

**Comment by Leigham** [comment]
@AnkouOSRS  this seems to still be an issue, looking through the code, none of the messages for the  onChatMessage event are firing. 
I have made a debug version of the plugin with lots of logging to try and narrow down the problem.

**Comment by Leigham** [comment]
I think it may be an issue with BOM in usernames.

**Comment by AnkouOSRS** [comment]
Interesting, I think you might be right about that. Calling Text.sanitize() on it will probably fix the issue if that's the case.

**Comment by AnkouOSRS** [comment]
I don't think its technically a BOM but possibly an issue with the character used for spaces

**Comment by Leigham** [comment]
@AnkouOSRS chatMessage.getName().replace("\u00a0"," ")  

according to runelite devs, its nbsp

**Comment by AnkouOSRS** [comment]
Text.sanitize() does that, as well as removing ironman symbols if they exist. I don't actually think the ironman symbol would make it in in any case, especially since I remove tags from the message, but I will update the plugin to call that method on both the text from the chat message as well as the local players name and that should hopefully fix this issue for good.

**Comment by AnkouOSRS** [comment]
I submitted the update. I will keep this issue open for now just in case it reoccurs for some people, please don't hesitate to let me know if it starts working for you on 1.3.2.
This issue has always baffled me as it only happened to some people, and I really didn't get more reports of it after the last update, so I was hoping it had been fixed. Everything makes sense now though, and I appreciate your help investigating @Leigham

**Comment by Leigham** [comment]
Yeah, it just seems to happen to a small amount of players having nbsp instead of spaces in their name, hopefully this fix will help other people that have plugins that compare names (raid tracker issue has been submitted too)

**Comment by Leigham** [comment]
can confirm, seems to be working with latest update.

**Comment by AnkouOSRS** [comment]
Awesome, I had another friend that was previously experiencing this issue confirm that it is now working for them as well. @Leigham grats on your purple (hope it was a good one) and thanks again for your assistance on this!
